name: Docker Compose Deploy
description: Despliega la app usando docker-compose con configuración de entorno específica.
inputs:
  environment:
    description: "Entorno de despliegue (dev, prd, stg, tst)"
    required: true
    default: "dev"
  # secrets_json:
  #   description: "Secrets en formato JSON"
  #   required: false
  
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure environment file
      run: |
        echo "Configurando entorno: ${{ inputs.environment }}"
        if [ -f ".env.${{ inputs.environment }}" ]; then
          cp ".env.${{ inputs.environment }}" .env
          echo "✅ Archivo .env.${{ inputs.environment }} copiado a .env"
          echo "Contenido del archivo .env:"
          cat .env
        else
          echo "❌ Error: Archivo .env.${{ inputs.environment }} no encontrado"
          echo "Archivos .env disponibles:"
          ls -la .env.* 2>/dev/null || echo "No se encontraron archivos .env.*"
          exit 1
        fi
      shell: bash
    - name: Process secrets
      run: |
        # Procesar secretos desde ALL_SECRETS y agregarlos al .env
        if [ ! -z "$ALL_SECRETS" ]; then
          echo "=== Procesando secretos ==="
          echo "Secretos recibidos:"
          echo "$ALL_SECRETS"
          echo ""
          
          # Agregar secretos al archivo .env (ya están en formato KEY=VALUE)
          echo "" >> .env
          echo "# === SECRETS AGREGADOS AUTOMÁTICAMENTE ===" >> .env
          echo "$ALL_SECRETS" >> .env
          
          echo "✅ Secretos agregados al archivo .env"
          echo ""
          echo "=== Archivo .env final ==="
          cat .env
          echo "=== EOF Archivo .env final ==="
        else
          echo "⚠️  No se encontraron secretos en ALL_SECRETS"
        fi
        
        echo ""
    - name: Process variables
      run: |
        # Procesar variables desde DOCKER_VARIABLES y agregarlos al .env
        if [ ! -z "$DOCKER_VARIABLES" ]; then
          echo "=== Procesando variables ==="
          echo "Variables recibidas:"
          echo "$DOCKER_VARIABLES"
          echo ""
          
          # Agregar variables al archivo .env (ya están en formato KEY=VALUE)
          echo "" >> .env
          echo "# === VARIABLES AGREGADOS AUTOMÁTICAMENTE ===" >> .env
          echo "$DOCKER_VARIABLES" >> .env

          echo "✅ Variables agregados al archivo .env"
          echo ""
          echo "=== Archivo .env final ==="
          cat .env
          echo "=== EOF Archivo .env final ==="
        else
          echo "⚠️  No se encontraron variables en DOCKER_VARIABLES"
        fi
        
      shell: bash
