name: Docker Compose Deploy
description: Despliega la app usando docker-compose con configuración de entorno específica.
inputs:
  environment:
    description: "Entorno de despliegue (dev, prd, stg, tst)"
    required: true
    default: "dev"
  secrets_json:
    description: "Secrets en formato JSON"
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure environment file
      run: |
        echo "Configurando entorno: ${{ inputs.environment }}"
        if [ -f ".env.${{ inputs.environment }}" ]; then
          cp ".env.${{ inputs.environment }}" .env
          echo "✅ Archivo .env.${{ inputs.environment }} copiado a .env"
          echo "Contenido del archivo .env:"
          cat .env
        else
          echo "❌ Error: Archivo .env.${{ inputs.environment }} no encontrado"
          echo "Archivos .env disponibles:"
          ls -la .env.* 2>/dev/null || echo "No se encontraron archivos .env.*"
          exit 1
        fi
      shell: bash
    - name: Process secrets and deploy
      run: |
        echo "Desplegando en entorno: ${{ inputs.environment }}"
        
        # Procesar secretos desde SECRETEISHONSS y agregarlos al .env
        if [ ! -z "$SECRETEISHONSS" ]; then
          echo "=== Procesando secretos ==="
          echo "Secretos recibidos:"
          echo "$SECRETEISHONSS"
          echo ""
          
          # Agregar secretos al archivo .env (ya están en formato KEY=VALUE)
          echo "" >> .env
          echo "# === SECRETS AGREGADOS AUTOMÁTICAMENTE ===" >> .env
          echo "$SECRETEISHONSS" >> .env
          
          echo "✅ Secretos agregados al archivo .env"
          echo ""
          echo "=== Archivo .env final ==="
          cat .env
          echo "=========================="
        else
          echo "⚠️  No se encontraron secretos en SECRETEISHONSS"
        fi
        
        echo ""
        echo "=== Variables de entorno disponibles ==="
        env | grep -E "(BASE_DE_DATOS|SECRETO|DOCKERHUB)" || echo "No se encontraron variables relevantes"
        echo "========================================"
        
        # docker-compose -f docker-compose.yml up -d --remove-orphans
      shell: bash
