name: Docker Compose Deploy
description: Despliega la app usando docker-compose con configuración de entorno específica.
inputs:
  environment:
    description: "Entorno de despliegue (dev, prd, stg, tst)"
    required: true
    default: "dev"
  
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Prepare Env => .env file (Step 1/3)
      run: |
        echo "Configurando archivo .env si existe. ${{ inputs.environment }}"
        if [ -f ".env.${{ inputs.environment }}" ]; then
          cp ".env.${{ inputs.environment }}" .env
          echo "✅ Archivo .env.${{ inputs.environment }} copiado a .env"
        else
          echo "⚠️  Advertencia: Archivo .env.${{ inputs.environment }} no encontrado"
          echo "Archivos .env disponibles:"
          ls -la .env.* 2>/dev/null || echo "No se encontraron archivos .env.*"
        fi
      shell: bash
    - name: Prepare Env => Process secrets (Step 2/3)
      run: | 
        # Procesar secretos y agregarlos al .env
        if [ ! -z "$ALL_SECRETS" ]; then
          echo "🔑 Se encontro la variable ALL_SECRETS, se inyectaran en .env"
          # Agregar secretos al archivo .env (ya están en formato KEY=VALUE)
          echo "" >> .env
          echo "# === SECRETS AGREGADOS AUTOMÁTICAMENTE ===" >> .env
          echo "$ALL_SECRETS" >> .env
          echo "✅ Secretos agregados al archivo .env"
        else
          echo "⚠️ No se encontraron secretos en ALL_SECRETS"
        fi
      shell: bash
    - name: Prepare Env => Process variables (Step 3/3)
      run: |
        # Procesar variables desde ENV_VARIABLES y agregarlos al .env
        if [ ! -z "$ENV_VARIABLES" ]; then
          echo "🔧 Se encontro la variable ENV_VARIABLES, se inyectaran en .env"

          # Agregar variables al archivo .env (ya están en formato KEY=VALUE)
          echo "" >> .env
          echo "# === VARIABLES AGREGADOS AUTOMÁTICAMENTE ===" >> .env
          echo "$ENV_VARIABLES" >> .env

          echo "✅ Variables agregados al archivo .env"
        else
          echo "⚠️  No se encontraron variables en ENV_VARIABLES"
        fi
      shell: bash
