name: CI App Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Compose Deploy
        uses: teranjoan/github-actions-templates/.github/actions/deploy-docker-full-cicd@master
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
