name: CI con Debug Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "production"
      API_URL: "https://api.midominio.com"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar dependencias
        run: |
          cd react-app
          npm install
      - name: Usar variable solo en este paso
        env:
          SOLO_PASO: "valor-unico"
        run: echo "Variable SOLO_PASO $SOLO_PASO"
      - name: Usar un secreto (debes crearlo en GitHub como MI_SECRETO)
        run: |
          echo "Token de acceso: ${{ secrets.ACCESS_TOKEN }}"
          echo "Clave API: ${{ secrets.API_KEY }}"
      - name: Run tests
        run: |
          cd react-app
          npm test -- --watchAll=false
      - name: Build app
        run: |
          cd react-app
          npm run build
      - name: Debug Workflow Action
        uses: ./.github/actions/debug-workflow
  fake_deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fake deploy step
        run: echo "Desplegando la app... (fake)"
      - name: Debug - Fin workflow
        run: echo "[DEBUG] Workflow CI-call-debug-action finalizado."
