name: Full Pipeline

on:
  workflow_call:
    secrets:
      dockerhub_user:
        required: true
      dockerhub_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build React App
        uses: teranjoan/GithubActions-cicd/.github/actions/build-react@master

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test React App
        uses: teranjoan/GithubActions-cicd/.github/actions/test-react@master

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Docker Build & Push
        uses: teranjoan/GithubActions-cicd/.github/actions/docker-build-push@master
        with:
          dockerhub_user: ${{ secrets.dockerhub_user }}
          dockerhub_password: ${{ secrets.dockerhub_password }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Docker Compose Deploy
        uses: teranjoan/GithubActions-cicd/.github/actions/docker-deploy-compose@master
