name: Full Pipeline

on:
  workflow_call:
    inputs:
      environment:
        description: "Entorno de despliegue (dev, prd, stg, tst)"
        required: true
        type: string
        default: "dev"
    # secrets:
    #   dockerhub_user:
    #     required: true
    #   dockerhub_password:
    #     required: true

jobs:
  # === DEMO: Using action that demonstrates passing variables between steps ===
  passing_values_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run passing values demo action
        id: demo
        uses: teranjoan/GithubActions-cicd/.github/actions/passing_values_between_jobs@master
        with:
          demo_prefix: "ActionDemo"
      
      - name: Use outputs from the action
        run: |
          echo "🎯 Outputs received from the action:"
          echo "  Generated Name: ${{ steps.demo.outputs.generated_name }}"
          echo "  Build Time: ${{ steps.demo.outputs.build_time }}"
          echo "  Build Number: ${{ steps.demo.outputs.build_number }}"
          echo ""
          echo "🔍 Parsing JSON output:"
          echo '${{ steps.demo.outputs.app_info_json }}' | jq '.'
          
          # Extract values from JSON output
          APP_NAME=$(echo '${{ steps.demo.outputs.app_info_json }}' | jq -r '.name')
          ENVIRONMENT=$(echo '${{ steps.demo.outputs.app_info_json }}' | jq -r '.environment')
          
          echo ""
          echo "📋 Using extracted JSON values:"
          echo "  App Name from JSON: $APP_NAME"
          echo "  Environment from JSON: $ENVIRONMENT"

  # === END DEMO ===

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Build React App
  #       uses: teranjoan/GithubActions/.github/actions/build-react@master

  # test:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   continue-on-error: true
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Test React App
  #       uses: teranjoan/GithubActions/.github/actions/test-react@master

  # docker:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Docker Build & Push
  #       uses: teranjoan/GithubActions/.github/actions/docker-build-push@master
  #       with:
  #         dockerhub_user: ${{ secrets.dockerhub_user }}
  #         dockerhub_password: ${{ secrets.dockerhub_password }}
  # deploy:
  #   runs-on: ubuntu-latest
  #   environment: ${{ inputs.environment }}
  #   # needs: docker
  #   steps:
  #     - name: "Prepare env file for ${{ inputs.environment }}"
  #       uses: teranjoan/GithubActions-cicd/.github/actions/prepare-env-file@master
  #       with:
  #         environment: ${{ inputs.environment }}
  #       env:
  #         # Pass secrets as environment variables to the action in KEY=VALUE format
  #         ALL_SECRETS: |
  #           MY_ENV_SECRET_1=${{ secrets.MY_ENV_SECRET_1 }}
  #           MY_ENV_SECRET_2=${{ secrets.MY_ENV_SECRET_2 }}
  #           MY_REPO_SECRET_1=${{ secrets.MY_REPO_SECRET_1 }}
  #           MY_REPO_SECRET_2=${{ secrets.MY_REPO_SECRET_2 }}
  #         ENV_VARIABLES: |
  #           # 
  #           MY_ENV_VAR_1=${{ vars.MY_ENV_VAR_1 }}
  #           MY_ENV_VAR_2=${{ vars.MY_ENV_VAR_2 }}

  #           MY_REPO_VAR_1=${{ vars.MY_REPO_VAR_1 }}
  #           MY_REPO_VAR_2=${{ vars.MY_REPO_VAR_2 }}

