name: Full Pipeline

on:
  workflow_call:
    inputs:
      environment:
        description: "Entorno de despliegue (dev, prd, stg, tst)"
        required: true
        type: string
        default: "dev"
    secrets:
      dockerhub_user:
        required: true
      dockerhub_password:
        required: true

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Build React App
  #       uses: teranjoan/GithubActions/.github/actions/build-react@master

  # test:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   continue-on-error: true
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Test React App
  #       uses: teranjoan/GithubActions/.github/actions/test-react@master

  # docker:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Docker Build & Push
  #       uses: teranjoan/GithubActions/.github/actions/docker-build-push@master
  #       with:
  #         dockerhub_user: ${{ secrets.dockerhub_user }}
  #         dockerhub_password: ${{ secrets.dockerhub_password }}
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}  # Esto permite acceder a las variables del entorno específico
    # needs: docker
    steps:
      - name: Docker Compose Deploy
        uses: teranjoan/GithubActions-cicd/.github/actions/docker-deploy-compose@master
        with:
          environment: ${{ inputs.environment }}
        env:
          # Pasar secrets como variables de entorno al action en formato KEY=VALUE
          ALL_SECRETS: |
            BASE_DE_DATOS_NAME=${{ secrets.BASE_DE_DATOS_NAME }}
            SECRETO_1=${{ secrets.SECRETO_1 }}
            SECRETO_4=${{ secrets.SECRETO_4 }}
            DOCKERHUB_USER=${{ secrets.DOCKERHUB_USER }}
            DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}
          ENV_VARIABLES: |
            # Variables adicionales para docker-compose
            MY_ENV_VAR=${{ vars.MY_ENV_VAR }}
            MY_REPO_VAR=${{ vars.MY_REPO_VAR }}